# Generated by Django 5.1.6 on 2025-03-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.IntegerField()),
                ('dept', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('event', models.CharField(max_length=20)),
            ],
        ),
    ]
