# Generated by Django 5.1.1 on 2025-03-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfestaapp', '0003_alter_paymentdetails_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='image',
            field=models.ImageField(upload_to='payment_images/'),
        ),
    ]
