# Generated by Django 5.1.1 on 2025-03-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfestaapp', '0004_alter_paymentdetails_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='payment_verified',
            field=models.BooleanField(default=False),
        ),
    ]
