# Generated by Django 5.1.6 on 2025-03-20 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dfestaapp', '0007_studentdetails_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetails',
            name='amount',
        ),
    ]
